### PR TITLE
Cleanup: remove real-time trip planning, other dead code, etc.

### PR DESCRIPTION
**Pull request by kurtraschke**
This PR has (approximately) the same content as onebusaway/onebusaway-application-modules#53, merged on top of camsys/onebusaway-application-modules@unified, as that appears to be where active development lives now.  It implements the removal of all OTP-related code and real-time trip planning support, along with other assorted bits of dead code (such as to support a study conducted with the Transportation Choices Coalition in 2010).

### CODE REVIEW

**Comment by sheldonabrown** [comment]
Thanks Kurt!

**Comment by sheldonabrown** [comment]
Also -- to be clear -- I intend to merge back the unified branch to the OneBusAway repo.  Its simply more convenient day-to-day releases out of the camsys repo and the long term releases out of the OneBusAway repo.

**Comment by kurtraschke** [comment]
Thanks!

**Comment by sheldonabrown** [comment]
Did you mean to delete the ApiKeyValidation service?  That's still in use by a couple of modules....

**Comment by kurtraschke** [comment]
@sheldonabrown I removed that code in f8041bdb6307b044047757fcf19554b5e490ded1 after finding it to be unused while [diagnosing](https://github.com/OneBusAway/onebusaway-application-modules/issues/145#issuecomment-138139542) onebusaway/onebusaway-application-modules#145; it's not actually part of the code path for API key validation in `onebusaway-api-webapp`, which instead uses `ApiKeyPermissionService`, which in turn depends on `UserService`.  I see now that that removal left dangling references in several `data-sources.xml` and `application-context-webapp.xml` files, but I don't see anywhere that an instance of `KeyValidationService` is actually injected.

**Comment by sheldonabrown** [comment]
@kurtraschke ok -- I've restored it mainly for the data-source references.  Early testing and configuration contradicts your explanation but I don't know the code well enough to say that authoritatively.

**Pull request merged**
